version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 4g
    ports:
      - "4441:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: selenium/standalone-firefox:latest
    hostname: firefox
    privileged: true
    shm_size: 4g
    ports:
      - "4442:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=4